apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.smokeTests.name }}-instances
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.smokeTests.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  instances.json: |
    {{- .Values.smokeTests.instancesJson | nindent 4 }}
