{{- if .Values.spark.vaultCertRenewal.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "datahub-v2-smoke-tests.fullname" . }}-spark-vault-cert-renew
  labels:
    app.kubernetes.io/name: {{ include "datahub-v2-smoke-tests.name" . }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
spec:
  refreshInterval: {{ .Values.spark.vaultCertRenewal.refreshInterval | quote }}
  target:
    name: {{ .Values.spark.vaultClientCert.secretName }}
    creationPolicy: Merge
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: '{{`{{ .certificate }}`}}'
        tls.key: '{{`{{ .private_key }}`}}'
        ca.crt: '{{`{{ .issuing_ca }}`}}'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: {{ include "datahub-v2-smoke-tests.fullname" . }}-spark-vault-cert-issue
{{- end }}
