{{- if .Values.spark.vaultCertRenewal.enabled }}
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: {{ include "datahub-v2-smoke-tests.fullname" . }}-spark-vault-cert-issue
  labels:
    app.kubernetes.io/name: {{ include "datahub-v2-smoke-tests.name" . }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
spec:
  path: {{ printf "%s/issue/%s" .Values.spark.vaultCertRenewal.pkiPath .Values.spark.vaultCertRenewal.pkiRole }}
  method: PUT
  resultType: Data
  parameters:
    common_name: {{ .Values.spark.vaultClientCert.commonName | quote }}
  provider:
    server: {{ .Values.spark.vaultCertRenewal.vaultServer | quote }}
    namespace: {{ .Values.spark.vaultCertRenewal.vaultNamespace | quote }}
    auth:
      cert:
        clientCert:
          secretRef:
            name: {{ .Values.spark.vaultClientCert.secretName }}
            key: tls.crt
        secretRef:
          name: {{ .Values.spark.vaultClientCert.secretName }}
          key: tls.key
{{- end }}
